apiVersion: v1
kind: Service
metadata:
  name: openvidu-server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: openvidu-server
  ports:
    - port: 8888
      targetPort: 8888
    - port: 4443
      targetPort: 4443
