apiVersion: v1
kind: Service
metadata:
  name: openvidu-server-kms-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: openvidu-server-kms
  ports:
    - port: 9091
      targetPort: 9091
    - port: 4443
      targetPort: 4443
